//DESSA NYCKLAR OCH VÄRDEN KASTAS IN I DROPDOWN MENY, URI OCH FETCH
export const categoriesToId = {
  general: 9,
  book: 10,
  movie: 11,
  music: 12,
  theatre: 13,
  television: 14,
  videogame: 15,
  boardgame: 16,
  science: 17,
  computer: 18,
  mathematics: 19,
  mythology: 20,
  sports: 21,
  geography: 22,
  history: 23,
  politics: 24,
  celebrity: 26,
  animal: 27,
  vehicle: 28,
  comics: 29,
  anime: 31,
  cartoon: 32,
};
